2023-12-14 18:00:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "HISTORY" not found (this database is empty); SQL statement:
INSERT INTO history (sn, `date`, voltage_input, voltage_output, frequency_input, frequency_output,
                             battery_voltage, battery_level, temperature, output_load_percent)
        VALUES (?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?) [42104-210]
2023-12-14 10:00:39 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:00:48 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:01:19 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:01:19 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:04:11 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:05:11 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 10:05:57 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 11:12:21 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 11:13:13 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 11:13:59 jdbc[5]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 19:14:38 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]" [50000-210]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3296)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:228)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:223)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:96)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:452)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:100)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseProductName(VendorDatabaseIdProvider.java:68)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseName(VendorDatabaseIdProvider.java:59)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseId(VendorDatabaseIdProvider.java:46)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.databaseIdProviderElement(XMLConfigBuilder.java:334)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:129)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parse(XMLConfigBuilder.java:110)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:80)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:66)
	at com.watson.monitor.utils.SqlUtil.getSqlSessionFactory(SqlUtil.java:15)
	at com.watson.monitor.Tmp3.main(Tmp3.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]" [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 32 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 26 more
2023-12-14 19:14:38 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]" [50000-210]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3296)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:228)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:223)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:96)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:452)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:100)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:145)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:348)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:89)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy6.insertOne(Unknown Source)
	at com.watson.monitor.Tmp3.main(Tmp3.java:26)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]" [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 36 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Administrator/Desktop/monitor/db/data.mv.db [2.1.210/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 30 more
2023-12-14 11:29:11 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 11:29:26 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-14 11:30:33 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1573)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:470)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-12-15 14:46:18 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 14:46:18 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 15:05:07 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 15:05:07 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 16:43:05 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 19:33:39 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 19:33:39 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-15 22:50:07 jdbc[8]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-21 16:34:44 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-21 16:34:44 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-23 21:03:15 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-23 21:03:15 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-25 11:30:52 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-25 11:37:06 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-25 11:37:07 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2023-12-28 11:21:19 jdbc[6]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.14/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2024-01-11 16:00:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.15/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.15/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
2024-01-11 16:04:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
	at com.h2database@2.1.210/org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:227)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:203)
	at com.h2database@2.1.210/org.h2.message.DbException.get(DbException.java:192)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
	at com.h2database@2.1.210/org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:423)
	at org.mybatis@3.5.15/org.apache.ibatis.datasource.pooled.PooledDataSource.forceCloseAll(PooledDataSource.java:367)
	at org.mybatis@3.5.15/org.apache.ibatis.datasource.pooled.PooledDataSource.finalize(PooledDataSource.java:625)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
